### ISSUE TITLE
mikmod-0.1.2.1 does not compile

### ISSUE THREAD

**Issue by peti** [evanrinehart/mikmod#1]
Citing from http://hydra.cryp.to/build/527703/nixlog/2/raw:

```
Building mikmod-0.1.2.1...
Preprocessing library mikmod-0.1.2.1...
Errors.hsc:19:20: fatal error: mikmod.h: No such file or directory
compilation terminated.
```

My guess is that your Cabal file doesn't declare the package's dependency on the `mikmod` library in `includes:` and/or `extra-libraries:` stanzas.

**Comment by evanrinehart** [comment]
Thanks for the tip, this was fixed in 0.1.3.1.
